# permissions for end users to edit loggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logger-editor-role
rules:
- apiGroups:
  - managed.openshift.io
  resources:
  - loggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed.openshift.io
  resources:
  - loggers/status
  verbs:
  - get
